### ISSUE TITLE
Compatibilty With latest blesta

### ISSUE THREAD

**Issue by Jawanet** [blesta/module-digitalocean#1]
What blesta developers can't fix this plugin ?

**Comment by timnboys** [comment]
I just did check my repo where I just fixed it at until the blesta developers get around to merging the codebase with the official one here.

**Comment by Jawanet** [comment]
Tanks for you work brother, if done i can send you litle donation.

**Comment by timnboys** [comment]
@Jawanet yes I am done with it; just waiting for paul and tyson to decide if it meets their standards and merge it already lol.
